# Generated by Django 3.2 on 2023-08-21 12:31

import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Любимый рецепт',
                'verbose_name_plural': 'Любимые рецепты',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Здесь нужно ввести название ингредиента.', max_length=64, verbose_name='Название ингредиента.')),
                ('measurement_unit', models.CharField(help_text='Здесь нужно ввести измерительную величину.', max_length=16, verbose_name='Измерительная величина.')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Здесь нужно добавить изображение.', upload_to='recipes/images/', verbose_name='Изображение.')),
                ('name', models.CharField(help_text='Здесь нужно ввести название рецепта.', max_length=200, verbose_name='Название рецепта.')),
                ('text', models.TextField(help_text='Здесь нужно ввести текст рецепта.', verbose_name='Описание рецепта.')),
                ('cooking_time', models.PositiveIntegerField(help_text='Здесь нужно ввести время приготовления.', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Готовить меньше минуты - значит есть сырым!')], verbose_name='Время приготовления.')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Количество должно быть больше 0.')], verbose_name='Количество ингредиента.')),
            ],
            options={
                'verbose_name': 'Ингредиенты для рецепта',
                'verbose_name_plural': 'Ингредиенты для рецепта',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Здесь нужно задать имя тэга.', max_length=200, verbose_name='Имя тэга.')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('slug', models.SlugField(help_text='Здесь нужно задать уникальный слаг тэга.', max_length=200, unique=True, verbose_name='Слаг тэга')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='recipes.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Корзина продуктов',
                'verbose_name_plural': 'Корзина продуктов',
            },
        ),
    ]
